### ISSUE TITLE
Custom Fonts Folder

### ISSUE THREAD

**Issue by sidhuparas** [knightcube/android-layout-templates#1]
There's no custom fonts folder as of now. Fancy layouts especially use custom fonts.

For nomenclature, I think a font named `Product Sans.ttf` should be renamed as `product_sans.ttf` which is default Android nomenclature. This will prevent duplication of fonts. This instruction can be added in README.

I can implement both the suggestions (fonts folder and updated README) with a PR. Should I go ahead?

**Comment by knightcube** [comment]
Sure! Go ahead.
