### ISSUE TITLE
Common folders for XML, screenshots, fonts and other resources.

### ISSUE THREAD

**Issue by DhruvamSharma** [knightcube/android-layout-templates#4]
Hi, 
I think there should be a common place for all the resources for a particular design layout. This will make the repository more easily searchable.

Keeping things separate will only make it more difficult to search in different folders.

|- Repository
    |- SampleLayout_1
    |     |- XML
    |     |- Fonts
    |     |- Screenshots
    |     |- Other Resources
    |
    |- SampleLayout_2
    |     |- XML
    |     |- Fonts
    |     |- Screenshots
    |     |- Other Resources

**Comment by Kvaibhav01** [comment]
Agreed. Kindly look into the matter @knightcube
